package nl.politie.buildtool.model

const val TITLE = "Rob's BuildTool"
const val LBL_SELECTED = "Selected"
const val LBL_POM_FILES = "Pom files"
const val LBL_MAVEN_PROJECTS = "Maven projects"
const val TOOLTIP_CLEAN = "Maven Clean"
const val TOOLTIP_INSTALL = "Maven Install"
const val TOOLTIP_COMPILE = "Maven Compile"
const val TOOLTIP_TEST = "Maven TEST"
const val TOOLTIP_GIT_PULL = "Perform a Git Pull on every git directory"
const val TOOLTIP_STOP_ON_ERROR = "Stop building when a build fails"
const val TOOLTIP_ORDERED_BUILD = "Build projects in order or not"
const val TXT_CLEAN = "clean"
const val TXT_COMPILE = "compile"
const val TXT_INSTALL = "install"
const val TXT_TEST = "test"
const val TXT_GIT_PULL = "Git Pull"
const val TXT_STOP_ON_ERROR = "Stop on error"
const val TXT_ORDERED_BUILD = "Ordered build"